### ISSUE TITLE
Missing bitstreams folder

### ISSUE THREAD

**Issue by amritamaz** [YihangChen-ee/CNC#1]
Hi, thank you for releasing your code! When trying to run the code with the nerf_synthetic dataset, I landed on a FileNotFound error:

```
Traceback (most recent call last):
  File "examples/train_CNC_nerf_synthetic.py", line 433, in <module>
    Pgs_dict, embed_bits_MB, embed_bits_MB_codec = entropy_estimator.encode_binary_vxl_mixPg_3D2D(
  File "/gpfs/fs1/projects/nvr_nxp_visionconferencing/users/amritam/CNC/examples/utils_bpp_acc.py", line 779, in encode_binary_vxl_mixPg_3D2D
    ttl_bit_n, ttl_num_n, encode_ttl_bit_n = forward_2D(params_q_xyz[self.offsets_list[-2]:self.offsets_list[-1]], idx_coords2, Ec, p, binary_vxl_2D, a)
  File "/gpfs/fs1/projects/nvr_nxp_visionconferencing/users/amritam/CNC/examples/utils_bpp_acc.py", line 722, in forward_2D
    encode_len_bit = encoder(xs, ps, filename_prefix + '_' + axis + str(n) +'.b')
  File "/gpfs/fs1/projects/nvr_nxp_visionconferencing/users/amritam/CNC/examples/utils_bpp_acc.py", line 91, in encoder
    with open(file_name, 'wb') as fout:
FileNotFoundError: [Errno 2] No such file or directory: './bitstreams/lego_xy0.b'
```

I added a `os.makedirs(os.path.dirname(file_name), exist_ok=True)` line just before `utils_bpp_acc:91` and that seemed to resolve the issue, but I am not sure if that is the suggested solution. Can you confirm if that is the right place to put the bitstreams folder? Thank you!

**Comment by YihangChen-ee** [comment]
Hi, thanks for pointing this out. Your solution is correct. I have now added a `os.makedirs('./bitstreams/' + args.scene, exist_ok=True)` in the training script, and it should solve the problem.
